<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>ee61c16a-3af1-4918-a0dc-62abfdd28087</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foodie.Common.Api\Foodie.Common.Api.csproj" />
    <ProjectReference Include="..\Foodie.EventBus\Foodie.EventBus.csproj" />
    <ProjectReference Include="..\Foodie.Orders.Application\Foodie.Orders.Application.csproj" />
    <ProjectReference Include="..\Foodie.Orders.Infrastructure\Foodie.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
