// <auto-generated />
using System;
using Foodie.Meals.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodie.Meals.Infrastructure.Migrations
{
    [DbContext(typeof(MealsDbContext))]
    partial class MealsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryRestaurant", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "RestaurantsId");

                    b.HasIndex("RestaurantsId");

                    b.ToTable("CategoryRestaurant");

                    b.HasData(
                        new
                        {
                            CategoriesId = 2,
                            RestaurantsId = 1
                        },
                        new
                        {
                            CategoriesId = 3,
                            RestaurantsId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            RestaurantsId = 3
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(6627), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(6689), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(6693), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(6695), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Salad"
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(6851), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Las Vegas"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7075), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7079), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "USA"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kfc Las Vegas",
                            CityId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7180), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "kfc.lasvegas@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kfc Los Angeles",
                            CityId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7205), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "kfc.losangeles@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kfc New York",
                            CityId = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7210), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "kfc.newyork@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Pizza Hut Las Vegas",
                            CityId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7214), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "pizzahut.lasvegas@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Pizza Hut Los Angeles",
                            CityId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7218), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "pizzahut.losangeles@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "McDonald's Las Vegas",
                            CityId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7225), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "mcdonalds.lasvegas@email.com",
                            PhoneNumber = "123-123-213",
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7447), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Longer",
                            Name = "Longer",
                            Price = 12m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7466), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Zinger",
                            Name = "Zinger",
                            Price = 10m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7472), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Pizza Texas",
                            Name = "Pizza Texas",
                            Price = 12m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7476), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Pizza Carbonara",
                            Name = "Pizza Carbonara",
                            Price = 12m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7480), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Big Mac",
                            Name = "Big Mac",
                            Price = 15m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7486), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "McRoyal",
                            Name = "McRoyal",
                            Price = 10m,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7704), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "KFC"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7713), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 20, 18, 45, 12, 144, DateTimeKind.Unspecified).AddTicks(7716), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "McDonald's"
                        });
                });

            modelBuilder.Entity("CategoryRestaurant", b =>
                {
                    b.HasOne("Foodie.Meals.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodie.Meals.Domain.Entities.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.City", b =>
                {
                    b.HasOne("Foodie.Meals.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Location", b =>
                {
                    b.HasOne("Foodie.Meals.Domain.Entities.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodie.Meals.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Locations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Meal", b =>
                {
                    b.HasOne("Foodie.Meals.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Meals")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Foodie.Meals.Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
